### ISSUE TITLE
 synchronization problem after last update (web-telegram  app)

### ISSUE THREAD

**Issue by elvecio** [Telegram-FOSS-Team/Telegram-FOSS#288]
after the last telegram-app update in f-droid (I  done yesterday in my phone), **my messages** are no longer synchronized between web-telegram and the android app, while the messages of others are still synchronized.

**Comment by elvecio** [comment]
now  works again.
I lost just 5/6 messages ( the first yesterday night)...
I do not know what's going on but I'll keep an eye out to see if it happens again ;)

**Comment by Pikari0** [comment]
Same problem here, it happen with messages received since update to 4.9.1A, and it's random.
It doesn't seems to be link to the fact that I've read or not the message on Desktop.
Probably a bug with new SQLite Update ?

**Comment by thermatk** [comment]
Hi!
Next will come 5.2, so all these issues should resolve themselves :)
5.2 already has latest sqlite in upstream, just in case

**Comment by Peque** [comment]
I flashed a new ROM and after installing `4.9.1a` Telegram-FOSS was not synchronizing previous conversations. So basically the conversations list on start was empty except for some groups.

Downgrading to `4.9.1` fixed it.

@thermatk I guess it is related to this issue, so no need to open a new one, right?

**Comment by Bubu** [comment]
How weird. Upgrading seems to work fine, a new install doesn't display any chats for me either.

I guess this *might* be the related crash?

```
01-24 00:55:44.444 16990 16990 W RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
01-24 00:55:44.444 16990 16990 W RecyclerView: java.lang.IllegalStateException:  org.telegram.ui.Components.RecyclerListView{ba0cea8 IFED.V... ......ID 0,0-1080,1686}, adapter:org.telegram.ui.Adapters.DialogsAdapter@5f5dc1, layout:org.telegram.ui.DialogsActivity$4@b71e966, context:org.telegram.ui.LaunchActivity@f81a4a7
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2800)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5199)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11794)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6983)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.Adapters.DialogsAdapter.notifyDataSetChanged(DialogsAdapter.java:164)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.DialogsActivity.didReceivedNotification(DialogsActivity.java:1737)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.NotificationCenter.postNotificationNameInternal(NotificationCenter.java:263)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.NotificationCenter.postNotificationName(NotificationCenter.java:240)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.MessagesController.loadDialogs(MessagesController.java:3402)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.DialogsActivity$9.onScrolled(DialogsActivity.java:1196)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.Components.RecyclerListView$2.onScrolled(RecyclerListView.java:796)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4862)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3930)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView.dispatchLayout(RecyclerView.java:3561)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.messenger.support.widget.RecyclerView.onLayout(RecyclerView.java:4103)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.Components.RecyclerListView.onLayout(RecyclerListView.java:948)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.DialogsActivity$3.onLayout(DialogsActivity.java:581)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.ActionBar.ActionBarLayout$LinearLayoutContainer.onLayout(ActionBarLayout.java:108)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at org.telegram.ui.ActionBar.DrawerLayoutContainer.onLayout(DrawerLayoutContainer.java:380)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
01-24 00:55:44.444 16990 16990 W RecyclerView: 	at android.view.View.layout(View.java:17641)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.os.Handler.handleCallback(Handler.java:751)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.os.Looper.loop(Looper.java:154)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-24 00:55:44.445 16990 16990 W RecyclerView: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Bubu** [comment]
I've disabled this version in f-droid now. We'll have 5.2.1 soon.

**Comment by Bubu** [comment]
Let's keep this open so people will find it.

**Comment by samoht0** [comment]
>How weird. Upgrading seems to work fine, a new install doesn't display any chats for me either.
My experience from a upgrade is, that they're displayed because locally cached. But new messages (arriving while app wasn't online) are *not* (never) displayed. Just new messages that arrive "live" while online come in.

**Comment by samoht0** [comment]
>How weird. Upgrading seems to work fine, a new install doesn't display any chats for me either.

My experience from a upgrade is, that they're displayed because locally cached. But new messages (arriving while app wasn't online) are not (never) displayed. Just new messages that arrive "live" while online come in.
(now the quote is OK)

**Comment by thermatk** [comment]
v5.2.1 won't have this problem, was an outlier
