### ISSUE TITLE
Is armeabi supported?

### ISSUE THREAD

**Issue by Sasha-Sorokin** [Telegram-FOSS-Team/Telegram-FOSS#335]
Unfortunately I have to use pretty old device and it's sad experience, because it does not support many applications, but I found you tried previously to enable support for armeabi (ARMv6) for Telegram. And while running recent version on my phone I encounter such a problem where it couldn't locate library for tmessages.30 (even that installation completes just fine):

<details>
<summary>logcat</summary>

```
I/dalvikvm(11482): Could not find method android.content.Context.startForegroundService, referenced from method org.telegram.messenger.ApplicationLoader.startPushService
W/dalvikvm(11482): VFY: unable to resolve virtual method 469: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
D/dalvikvm(11482): VFY: replacing opcode 0x6e at 0x0059
I/dalvikvm(11482): Could not find method android.content.Context.getExternalMediaDirs, referenced from method androidx.core.content.FileProvider.parsePathStrategy
W/dalvikvm(11482): VFY: unable to resolve virtual method 446: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;
D/dalvikvm(11482): VFY: replacing opcode 0x6e at 0x00a0
W/System.err(11482): java.lang.UnsatisfiedLinkError: Couldn't load tmessages.30 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.telegram.messenger.beta-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.telegram.messenger.beta-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/System.err(11482):    at java.lang.Runtime.loadLibrary(Runtime.java:358)
W/System.err(11482):    at java.lang.System.loadLibrary(System.java:526)
W/System.err(11482):    at org.telegram.messenger.NativeLoader.initNativeLibs(NativeLoader.java:120)
W/System.err(11482):    at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:173)
W/System.err(11482):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err(11482):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4506)
W/System.err(11482):    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
W/System.err(11482):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
W/System.err(11482):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(11482):    at android.os.Looper.loop(Looper.java:136)
W/System.err(11482):    at android.app.ActivityThread.main(ActivityThread.java:5179)
W/System.err(11482):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(11482):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(11482):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
W/System.err(11482):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
W/System.err(11482):    at dalvik.system.NativeStart.main(Native Method)
E/tmessages(11482): Library not found, arch = armeabi
W/System.err(11482): java.lang.Exception: Unable to find file in apk:lib/armeabi/tmessages.30
W/System.err(11482):    at org.telegram.messenger.NativeLoader.loadFromZip(NativeLoader.java:67)
W/System.err(11482):    at org.telegram.messenger.NativeLoader.initNativeLibs(NativeLoader.java:197)
W/System.err(11482):    at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:173)
W/System.err(11482):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err(11482):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4506)
W/System.err(11482):    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
W/System.err(11482):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
W/System.err(11482):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(11482):    at android.os.Looper.loop(Looper.java:136)
W/System.err(11482):    at android.app.ActivityThread.main(ActivityThread.java:5179)
W/System.err(11482):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(11482):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(11482):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
W/System.err(11482):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
W/System.err(11482):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(11482): java.lang.UnsatisfiedLinkError: Couldn't load tmessages.30 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.telegram.messenger.beta-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.telegram.messenger.beta-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/System.err(11482):    at java.lang.Runtime.loadLibrary(Runtime.java:358)
W/System.err(11482):    at java.lang.System.loadLibrary(System.java:526)
W/System.err(11482):    at org.telegram.messenger.NativeLoader.initNativeLibs(NativeLoader.java:205)
W/System.err(11482):    at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:173)
W/System.err(11482):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err(11482):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4506)
W/System.err(11482):    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
W/System.err(11482):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
W/System.err(11482):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(11482):    at android.os.Looper.loop(Looper.java:136)
W/System.err(11482):    at android.app.ActivityThread.main(ActivityThread.java:5179)
W/System.err(11482):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(11482):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(11482):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
W/System.err(11482):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
W/System.err(11482):    at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(11482): No implementation found for native Lorg/telegram/tgnet/ConnectionsManager;.native_setJava:(Z)V
D/AndroidRuntime(11482): Shutting down VM
W/dalvikvm(11482): threadid=1: thread exiting with uncaught exception (group=0x4167fc20)
E/AndroidRuntime(11482): FATAL EXCEPTION: main
E/AndroidRuntime(11482): Process: org.telegram.messenger.beta, PID: 11482
E/AndroidRuntime(11482): java.lang.UnsatisfiedLinkError: Native method not found: org.telegram.tgnet.ConnectionsManager.native_setJava:(Z)V
E/AndroidRuntime(11482):        at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
E/AndroidRuntime(11482):        at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:174)
E/AndroidRuntime(11482):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(11482):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4506)
E/AndroidRuntime(11482):        at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E/AndroidRuntime(11482):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
E/AndroidRuntime(11482):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11482):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(11482):        at android.app.ActivityThread.main(ActivityThread.java:5179)
E/AndroidRuntime(11482):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11482):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(11482):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(11482):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(11482):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  474):   Force finishing activity org.telegram.messenger.beta/org.telegram.ui.LaunchActivity
```

</details>

After years, is armeabi still supported by your fork and if so — do you think is this problem specific to my phone? :frowning_face:

**Phone**: Samsung GT-S5660 Galaxy Gio (yeeeeeah, 2011....)
**Android version**: 4.4.4
**CyanogenMod version**: 11.0-20141206
**Kernel version**: 2.6.35.7-androidarmv6+
**CPU**: ARMv6-compatible processor rev 5 (v6l)

**Comment by r4sas** [comment]
As I remember, last correctly worked version was 3.18.0c. You can find APK in f-droid archive.

**Comment by Sasha-Sorokin** [comment]
Unfortunately nope, it does not work for almost the same reason. Tried to build on my own, ffmpeg fails to build. I guess armv6 not supported. Welp, not a big deal.
