### ISSUE TITLE
Crash on app start on x86

### ISSUE THREAD

**Issue by s09bQ5** [Telegram-FOSS-Team/Telegram-FOSS#560]
Hi, I'm running Telegram in an x86 Android 6 VM and I updated it from 5.15.0 to 8.2.7 using F-Droid. It now crashes immediately when I try to start the app. How can I debug this?

**Comment by Younes-L** [comment]
you could grab a crashlog the same way as you would do with any other app... but here are some key points you might be missing : 
* telegram-foss does not have x86 or x86-64 builds on f-droid, those builds on f-droid are only for armv7 and armv8
* currently it's unknown how telegram upstream make their x86 builds, so telegram-foss cannot make x86 builds
* this problem has recently gotten further towards a solution, join the tfossofftopic group using the newest invite link here https://t.me/tfossofftop and read this thread https://t.me/c/1096467410/128951?thread=111505
* if you still want to get crashlogs, consider this https://github.com/TacoTheDank/Scoop
* btw, telegram 5.15 does not exist ;-)

**Comment by s09bQ5** [comment]
The F-Droid APK doesn't even contain libtmessages for armv7!

Anyway, the crash log is
```
FATAL EXCEPTION: main
Process: org.telegram.messenger, PID: 2952
java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z)
	at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
	at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:195)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4705)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5415)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

Understandable that calling a native method fails when there is no library that implements it.

It might be that I remember the old version number incorrectly, but it was definitely a 5.x version. And version 5.15 did exist:
https://gitlab.com/fdroid/fdroiddata/-/commit/42f48bd38473d347125cfae77dbc1dd09be65e55
At first I thought I had the official non-FOSS build installed, but when I installed the new APK from the Telegram website, it didn't replace the old version and wanted to create a new account. When F-Droid told be that I can update, I thought that was how I installed it initially.

**Comment by s09bQ5** [comment]
8.4.2 from F-Droid works.
